# Generated by Django 6.0.4 on 2026-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_projeto_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('real', 'Projeto Real'), ('futuro', 'Projeto Futuro')], default='real', max_length=10),
        ),
    ]
