# Generated by Django 6.0.4 on 2026-04-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projeto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('instituicao', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='certificados/')),
            ],
        ),
    ]
