# Generated by Django 6.0.4 on 2026-06-02 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('resumo', models.TextField(max_length=400)),
                ('conteudo', models.TextField()),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='lab/publicacoes/')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Link externo do video')),
                ('video_arquivo', models.FileField(blank=True, null=True, upload_to='lab/videos/')),
                ('tecnologias_utilizadas', models.TextField(blank=True)),
                ('aprendizados_principais', models.TextField(blank=True)),
                ('dificuldades_encontradas', models.TextField(blank=True)),
                ('solucao_aplicada', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicacao de estudo',
                'verbose_name_plural': 'Publicacoes de estudo',
                'ordering': ('-criado_em', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='TemaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('descricao_curta', models.TextField(max_length=300)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='lab/temas/')),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tema de estudo',
                'verbose_name_plural': 'Temas de estudo',
                'ordering': ('ordem', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='ImagemPublicacaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='lab/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=150)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_extras', to='core.publicacaoestudo')),
            ],
            options={
                'verbose_name': 'Imagem extra da publicacao',
                'verbose_name_plural': 'Imagens extras da publicacao',
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.AddField(
            model_name='publicacaoestudo',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='core.temaestudo'),
        ),
        migrations.AlterUniqueTogether(
            name='publicacaoestudo',
            unique_together={('tema', 'slug')},
        ),
    ]
