# Generated by Django 6.0.4 on 2026-06-02 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publicacaoestudo_temaestudo_imagempublicacaoestudo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profissional/empresas/')),
                ('cargo', models.CharField(max_length=120)),
                ('periodo', models.CharField(max_length=80, verbose_name='periodo')),
                ('descricao_curta', models.TextField(max_length=350)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa profissional',
                'verbose_name_plural': 'Empresas profissionais',
                'ordering': ('ordem', '-criado_em', 'nome'),
            },
        ),
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170)),
                ('resumo', models.TextField(max_length=450)),
                ('atividades_realizadas', models.TextField()),
                ('aprendizados_obtidos', models.TextField()),
                ('habilidades_desenvolvidas', models.TextField(blank=True)),
                ('ferramentas_competencias', models.TextField(blank=True, verbose_name='tecnologias, ferramentas e competencias utilizadas')),
                ('desafios_enfrentados', models.TextField(blank=True)),
                ('resultados_alcancados', models.TextField(blank=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='profissional/experiencias/')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='core.empresaprofissional')),
            ],
            options={
                'verbose_name': 'Experiencia profissional',
                'verbose_name_plural': 'Experiencias profissionais',
                'ordering': ('-criado_em', 'titulo'),
                'unique_together': {('empresa', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ImagemExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='profissional/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=150)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core.experienciaprofissional')),
            ],
            options={
                'verbose_name': 'Imagem da experiencia profissional',
                'verbose_name_plural': 'Imagens da experiencia profissional',
                'ordering': ('ordem', 'id'),
            },
        ),
    ]
