# Generated by Django 6.0.4 on 2026-06-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empresaprofissional_experienciaprofissional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='aprendizado_obtido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='problema_resolvido',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='proximos_passos',
            field=models.TextField(blank=True),
        ),
    ]
