# Generated by Django 6.0.4 on 2026-06-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projeto_aprendizado_obtido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('nome',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
