"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@qzvjki5b#zdvo#)1g8nf)fu8+lp_=o**s+30!v=2n(cqfpm%5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


JAZZMIN_SETTINGS = {
    "site_title": "Lucas Admin",
    "site_header": "Lucas Admin",
    "site_brand": "Lucas Admin",
    "welcome_sign": "Bem-vindo ao painel administrativo do portfolio",
    "copyright": "Lucas Alves",
    "search_model": ["core.Projeto", "core.Certificado", "core.Tag"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "related_modal_active": True,
    "show_ui_builder": True,
    "show_theme_chooser": True,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "core.tag": "single",
    },
    "order_with_respect_to": [
        "core",
        "core.projeto",
        "core.tag",
        "core.certificado",
        "auth",
    ],
    "topmenu_links": [
        {
            "name": "Dashboard",
            "url": "admin:index",
            "icon": "fas fa-tachometer-alt",
        },
        {
            "name": "Portfolio",
            "url": "/",
            "new_window": True,
            "icon": "fas fa-external-link-alt",
        },
        {
            "model": "core.Projeto",
        },
        {
            "model": "core.Certificado",
        },
    ],
    "usermenu_links": [
        {
            "name": "Ver portfolio",
            "url": "/",
            "new_window": True,
            "icon": "fas fa-globe",
        },
    ],
    "icons": {
        "auth": "fas fa-user-shield",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "core": "fas fa-layer-group",
        "core.projeto": "fas fa-project-diagram",
        "core.tag": "fas fa-tags",
        "core.certificado": "fas fa-certificate",
    },
    "default_icon_parents": "fas fa-folder-tree",
    "default_icon_children": "fas fa-circle",
}


JAZZMIN_UI_TWEAKS = {
    "theme": "cyborg",
    "default_theme_mode": "dark",
    "accent": "accent-info",
    "navbar": "navbar-dark bg-primary",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "brand_colour": "navbar-primary",
    "brand_small_text": False,
    "button_classes": {
        "primary": "btn-info",
        "secondary": "btn-outline-light",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
